export const colorOptions = [
    { value: 'hsl(var(--custom-color-1))', label: 'Red' },
    { value: 'hsl(var(--custom-color-2))', label: 'Orange' },
    { value: 'hsl(var(--custom-color-3))', label: 'Amber' },
    { value: 'hsl(var(--custom-color-4))', label: 'Yellow' },
    { value: 'hsl(var(--custom-color-5))', label: 'Lime' },
    { value: 'hsl(var(--custom-color-6))', label: 'Avocado' },
    { value: 'hsl(var(--custom-color-7))', label: 'Green' },
    { value: 'hsl(var(--custom-color-8))', label: 'Emerald' },
    { value: 'hsl(var(--custom-color-9))', label: 'Teal' },
    { value: 'hsl(var(--custom-color-10))', label: 'Cyan' },
    { value: 'hsl(var(--custom-color-11))', label: 'Sky' },
    { value: 'hsl(var(--custom-color-12))', label: 'Blue' },
    { value: 'hsl(var(--custom-color-13))', label: 'Indigo' },
    { value: 'hsl(var(--custom-color-14))', label: 'Violet' },
    { value: 'hsl(var(--custom-color-15))', label: 'Purple' },
    { value: 'hsl(var(--custom-color-16))', label: 'Magenta' },
    { value: 'hsl(var(--custom-color-17))', label: 'Fuchsia' },
    { value: 'hsl(var(--custom-color-18))', label: 'Pink' },
    { value: 'hsl(var(--custom-color-19))', label: 'Rose' },
    { value: 'hsl(var(--custom-color-20))', label: 'Brown' },
    { value: 'hsl(var(--custom-color-21))', label: 'Warm Gray' },
    { value: 'hsl(var(--custom-color-22))', label: 'Cool Gray' },
    { value: 'hsl(var(--custom-color-23))', label: 'Salmon' },
    { value: 'hsl(var(--custom-color-24))', label: 'Peach' },
    { value: 'hsl(var(--custom-color-25))', label: 'Banana' },
    { value: 'hsl(var(--custom-color-26))', label: 'Mint' },
    { value: 'hsl(var(--custom-color-27))', label: 'Aqua' },
    { value: 'hsl(var(--custom-color-28))', label: 'Baby Blue' },
    { value: 'hsl(var(--custom-color-29))', label: 'Lavender' },
    { value: 'hsl(var(--custom-color-30))', label: 'Baby Pink' },
];
